version: 2.1

jobs:
  verify:
    working_directory: ~/dspace-example-modules

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - restore_cache:
          key: circleci-dspace-example-modules-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run:
          name: Generate the DSpace test harness
          command: mvn generate-test-resources
      - save_cache:
          paths:
            - ~/.m2
            - ~/dspace-example-modules/target
          key: circleci-dspace-example-modules-{{ checksum "pom.xml" }}
      - run: mvn verify test
      - store_test_results:
          path: target/surefire-reports

workflows:
  maven_test:
    jobs:
      - verify
